### ISSUE TITLE
Re-import news and announcements

### ISSUE THREAD

**Issue by rofe** [hlxsites/upm#1]
I think we should reimport those based on the examples in the `articles` folder.
- [ ] add both under `/articles`
- [x] use human readable file names
- [ ] remove header and footer
- [ ] add metadata block with `tags` (either `news` or `announcement`)

**Comment by mikew8** [comment]
The links from the main page for News and Announcements have been imported to the sharepoint site. They are in the folders of the same name. It would be good to have date folders like yyy-mm-dd, but the articles did not have a specific date they were created on, on them. We could create the date structure and use any date on the page, but I thought it might be confusing.

**Comment by mikew8** [comment]
Pages have been re-imported and organized into a folder with metadata of 'tag' to differentiate the pages from each other.
